[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-9_x"]

[phases.install]
cmds = [
  "npm ci --only=production",
  "cd frontend && npm ci --only=production"
]

[phases.build]
cmds = [
  "cd frontend && npm run build",
  "npm run build"
]

[start]
cmd = "npm start"
